Repository pylhc/PyLHC, pull requests merged in 2021-11, with the labels that each got.

#83 Proper CERN extra and readiness for release
  setup.py
Labels: enhancement, release

#85 Machine info run III
  doc/modules/constants.rst
  pylhc/calibration/beta.py
  pylhc/calibration/dispersion.py
  pylhc/data_extract/lsa.py
  pylhc/machine_settings_info.py
  setup.py
Labels: enhancement, bug, documentation, feature, release

#86 Docstring fixes in BPM calibration code
  pylhc/bpm_calibration.py
  pylhc/calibration/beta.py
Labels: enhancement

#88 License change and version update
  LICENSE
  README.md
  pylhc/__init__.py
  setup.py
Labels: release
